# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 23:19
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.AddField(
            model_name='post',
            name='color',
            field=colorfield.fields.ColorField(default='#8B4513', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='movement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
